---
title: "Combining"
author: "Vignesh J M"
date: 2020-09-04
description: "-"
type: technical_note
draft: false
---

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('diabetes.csv')
df2 = pd.read_csv('heart.csv')

In [3]:
pd.concat([df, df2])

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,age,...,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,6.0,148.0,72.0,35.0,0.0,33.6,0.627,50.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,85.0,66.0,29.0,0.0,26.6,0.351,31.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,8.0,183.0,64.0,0.0,0.0,23.3,0.672,32.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.0,...,221.0,0.0,1.0,164.0,1.0,0.0,2.0,0.0,2.0,1.0
1021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.0,...,258.0,0.0,0.0,141.0,1.0,2.8,1.0,1.0,3.0,0.0
1022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.0,...,275.0,0.0,0.0,118.0,1.0,1.0,1.0,1.0,2.0,0.0
1023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,...,254.0,0.0,0.0,159.0,0.0,0.0,2.0,0.0,2.0,1.0
1024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.0,...,188.0,0.0,1.0,113.0,0.0,1.4,1.0,1.0,3.0,0.0